name: CI Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Grant execute permission for hello.sh
        run: chmod +x ./hello.sh

      - name: Run hello script
        run: ./hello.sh

      - name: Run hello script
        run: ./hello.sh
